Models/LoanApplication.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeLoan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanApplication
    {
        public int LoanId { get; set; }
        public string PropertyLocation { get; set; }
        public string PropertyName { get; set; }
        public decimal EstimatedCostOfProperty { get; set; }
        public decimal AmountRequired { get; set; }
        public decimal MonthlyIncome { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public decimal AadharNumber { get; set; }
        public string PanNumber { get; set; }
        public bool Verified { get; set; }
        public bool Approved { get; set; }
    }
}

Controllers/LoanApplicationController.cs
using HomeLoan.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HomeLoan.Controllers
{
    public class LoanApplicationController : Controller
    {

       
        // GET: LoanApplication
        public ActionResult SaveFile()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SaveFile(HttpPostedFileBase file,HttpPostedFileBase file1,HttpPostedFileBase file2)
        {
            string path = Server.MapPath("~/App_Data/File");
            string fileName = Path.GetFileName(file.FileName);
            string fileName1 = Path.GetFileName(file1.FileName);
            string filename2 = Path.GetFileName(file2.FileName);

            string fullPath = Path.Combine(path, fileName);
            string combinepath = Path.Combine(path, fileName1);
            string combinepath1 = Path.Combine(path, filename2);

            file.SaveAs(fullPath);
            file1.SaveAs(combinepath);
            file2.SaveAs(combinepath1);
            if (file == null)
            {
                return View();
            }

            return RedirectToAction("LoanTracker");
        }


       [Authorize]
        public ActionResult Application()
        {

            LoanApplication Loanapp = new LoanApplication();

            return View(Loanapp);
        }


        [HttpPost]
        public ActionResult Application(LoanApplication LoanApp)
        {

            using (HomeLoanSiteEntities1 dbmodel = new HomeLoanSiteEntities1())
            {
                if(dbmodel.LoanApplications.Any(x=> x.PanNumber  == LoanApp.PanNumber))
                    {
                    ViewBag.DuplicateMessage = "Already Apllied on this PanNumber";
                    return View("Application", LoanApp);
                }
                dbmodel.LoanApplications.Add(LoanApp);
                try
                {
                   
                    dbmodel.SaveChanges();

                }
                catch (DbEntityValidationException dbEx)
                {

                    //Console.WriteLine(dbEx);
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                           


                            return  View("Application");
                        }
                    }
                }

            }
            ModelState.Clear();
                return RedirectToAction("SaveFile");
        }


        [Authorize]
        public ActionResult LoanTracker(LoanApplication loanapp)
        {
            using(HomeLoanSiteEntities1 dbmodel =new HomeLoanSiteEntities1())
            {
                var sql = (dbmodel.LoanApplications.Where(x => x.Verified == true).Count());

               
                if(sql >0 )
                {
                    ViewBag.DuplicateMessage = "Your application is verified sent for approval";
                    return View("LoanTracker");
                    var approval = (dbmodel.LoanApplications.Where(x => x.Approved == true).Count());
                    if (approval>0)
                    {
                        ViewBag.DuplicateMessage = "Your application is approved money will transfer soon";
                        return View("loanTracker");
                    }
                }
                else
                {
                    ViewBag.NewMessage = "Not Verified wait for verification";
                    return View("LoanTracker");
                }
                
            }
            return View();
        }


       






    }
}

Views/LoanApplication/Application.cshtml
@model HomeLoan.Models.LoanApplication

@{
    ViewBag.Title = "Application";
}

<h2>Application</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>LoanApplication</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <div class="col-md-offset-2 col-md-2">
            <label class=" alert-danger">@ViewBag.DuplicateMessage</label>
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.PropertyLocation, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PropertyLocation, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PropertyLocation, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PropertyName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PropertyName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PropertyName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EstimatedCostOfProperty, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EstimatedCostOfProperty, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EstimatedCostOfProperty, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AmountRequired, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AmountRequired, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AmountRequired, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MonthlyIncome, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MonthlyIncome, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MonthlyIncome, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DateOfBirth, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AadharNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AadharNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AadharNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PanNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PanNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PanNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Verified, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Verified, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Verified, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Approved, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Approved, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Approved, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Next" class="btn btn-default" />
        </div>
    </div>

</div>
}

Views/LoanApplication/LoanTracker.cshtml
@{
    ViewBag.Title = "LoanTracker";
}

<h2>LoanTracker</h2>





<label> Status </label> @ViewBag.NewMessage
<br />
<br />
<label>Status</label>  @ViewBag.DuplicateMessage

Views/LoanApplication/SaveFile.cshtml
@{
    ViewBag.Title = "SaveFile";
}

<h2>SaveFile</h2>

@using (Html.BeginForm("SaveFile", "LoanApplication", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div>
    upload your Aadhar
    @Html.TextBox("file", "", new { type = "File" })
    <br />

    <br />
    upload your Pan
    @Html.TextBox("file1", "", new { type = "File" })


    <br />
    <br/>
    Upload Your Collatral
    @Html.TextBox("file2", "", new { type = "File" })

    <br/>
    <input type="submit" value="Upload" />
</div>
}






   